// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface UserProp {
    user:     User;
    stats:    Stats;
    itemList: any[];
}

export interface Stats {
    followerCount:  number;
    followingCount: number;
    heart:          number;
    heartCount:     number;
    videoCount:     number;
    diggCount:      number;
}

export interface User {
    id:             string;
    shortId:        string;
    uniqueId:       string;
    nickname:       string;
    avatarLarger:   string;
    avatarMedium:   string;
    avatarThumb:    string;
    signature:      string;
    createTime:     number;
    verified:       boolean;
    secUid:         string;
    ftc:            boolean;
    relation:       number;
    openFavorite:   boolean;
    commentSetting: number;
    duetSetting:    number;
    stitchSetting:  number;
    privateAccount: boolean;
    secret:         boolean;
    isADVirtual:    boolean;
    roomId:         string;
}
